package com.example.mybatis.entity;

import java.util.Date;

public class OrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.id
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.order_num
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    private String orderNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.gmt_created
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    private Date gmtCreated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.create_by
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    private Integer createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.gmt_modify
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    private Date gmtModify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.modify_by
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    private Integer modifyBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.enabled_flag
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    private Byte enabledFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.id
     *
     * @return the value of order_item.id
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.id
     *
     * @param id the value for order_item.id
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.order_num
     *
     * @return the value of order_item.order_num
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    public String getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.order_num
     *
     * @param orderNum the value for order_item.order_num
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    public void setOrderNum(String orderNum) {
        this.orderNum = orderNum == null ? null : orderNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.gmt_created
     *
     * @return the value of order_item.gmt_created
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.gmt_created
     *
     * @param gmtCreated the value for order_item.gmt_created
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.create_by
     *
     * @return the value of order_item.create_by
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.create_by
     *
     * @param createBy the value for order_item.create_by
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.gmt_modify
     *
     * @return the value of order_item.gmt_modify
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.gmt_modify
     *
     * @param gmtModify the value for order_item.gmt_modify
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.modify_by
     *
     * @return the value of order_item.modify_by
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    public Integer getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.modify_by
     *
     * @param modifyBy the value for order_item.modify_by
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    public void setModifyBy(Integer modifyBy) {
        this.modifyBy = modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.enabled_flag
     *
     * @return the value of order_item.enabled_flag
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    public Byte getEnabledFlag() {
        return enabledFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.enabled_flag
     *
     * @param enabledFlag the value for order_item.enabled_flag
     *
     * @mbg.generated Tue Sep 29 02:12:56 CST 2020
     */
    public void setEnabledFlag(Byte enabledFlag) {
        this.enabledFlag = enabledFlag;
    }
}